### ISSUE TITLE
It is possible to update the Dockerfile to be able to run gstreamer the version you use, because I have not managed to install.

### ISSUE THREAD

**Issue by McL1V3** [avstack/gst-meet#15]

**Comment by jbg** [comment]
At the moment we're waiting for the stable GStreamer 1.20 release before updating the Dockerfile, because then binary packages will become available. Until then, the Dockerfile would probably have to build GStreamer 1.19.x from source.

If someone wants to contribute a multi-stage Dockerfile that builds GStreamer from source, that would be great. Otherwise I'll add this to our backlog, but no promise we'll get to it before the GStreamer 1.20 release.
