### ISSUE TITLE
Using JWT token auth with gst-meet

### ISSUE THREAD

**Issue by mwllgr** [avstack/gst-meet#45]
Hello,
is gst-meet able to authenticate via a generated JWT token?

I just checked my JS logs for the format and it looks like this:
`wss://jitsi.example.com/xmpp-websocket?room=lobby&token=jwt-token-value`

**Comment by mwllgr** [comment]
Thanks for the quick reply! I'd love to have JWT support but I've never written a single line in Rust. Maybe you could point me into the right direction? If it's only the thing to "append" the variable to the web socket link then I might be able to play around with it a bit.

**Comment by jbg** [comment]
Ah, we have phased out our Alpine repo because Alpine [now has GStreamer 1.20 in the official repo](https://pkgs.alpinelinux.org/packages?name=gstreamer&branch=edge) but looks like the Dockerfile in this project hasn't been updated yet. Will take care of that tomorrow, thanks for the heads up!

The WebSocket URL is built [here](https://github.com/avstack/gst-meet/blob/master/lib-gst-meet/src/xmpp/connection.rs#L80). I think we'd want to define another variant of the [Authentication enum](https://github.com/avstack/gst-meet/blob/master/lib-gst-meet/src/xmpp/connection.rs#L68) above that, something like `Jwt { token: String }`. Then in `Connection::new`, if `authentication` is that variant, we would add the token to the URL and set `authentication` to `Anonymous` (because the in-band XMPP authentication should still be `ANONYMOUS`). If you want to tackle it, go for it, otherwise we will get to it soon!

**Comment by mwllgr** [comment]
Oh, that makes everything a lot easier. Nice, thanks!
The whole auth enum thing makes sense. Will check it out in the next week or so but can't promise anything.

**Comment by mwllgr** [comment]
Hi, any news on the new Dockerfile?
